spring:
  application:
    name: Yaqazah
  docker:
    compose:
      enabled: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/yaqazah_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:0000}
    driver-class-name: org.postgresql.Driver

#  datasource:
#    url: jdbc:postgresql://postgres:5432/yaqazah_db # 'postgres' is the service name
#    username: ${DB_USERNAME:postgres}
#    password: ${DB_PASSWORD:0000}
#    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true  # Add this

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: ${REDIS_SSL:true}
  cache:
    type: redis


jwt:
  secret: ${JWT_SECRET:my-32-char-ultra-secret-key-12345}
  expiration: ${JWT_EXPIRATION:86400000}

encryption:
  key: ${DB_ENCRYPTION_KEY:my-32-char-ultra-secret-key-12345}

#minio:
#  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
#  access-key: ${MINIO_ACCESS_KEY:minioadmin}
#  secret-key: ${MINIO_SECRET_KEY:minioadmin}
#  bucket-name: ${MINIO_BUCKET:snapshots}

azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING:fake-connection-string-so-github-passes}
    container-name: ${AZURE_STORAGE_CONTAINER_NAME:fake-container-name}


cloudinary:
  cloud-name: ${cloudinary_cloud_name:fake-cloud-name}
  api-key: ${cloudinary_api_key:fake-api-key}
  api-secret: ${cloudinary_api_secret:fake-api-secret}

#app:
#  security:
#    # This tells Spring: "Look for an environment variable named API_KEY on Azure.
#    # If you are running locally and can't find it, use 'yaqazah_dev_key_123'."
#    api-key: ${API_KEY}

#stripe:
#  api:
#    key: ${STRIPE_SECRET_KEY}


########################################################
#spring:
#  application:
#    name: Yaqazah
#  datasource:
#    url: jdbc:postgresql://localhost:5432/yaqazah_db
#    username: postgres
#    password: "0000"
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: your-email@gmail.com
#    password: your-app-password
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#
#  data:
#    redis:
#      host: localhost
#      port: 6379
#
#  cache:
#    type: redis

# MINIO GOES HERE, AT THE ROOT LEVEL (NO INDENTATION)
#minio:
#  endpoint: localhost:9000
#  access-key:
#  secret-key:
#  bucket-name: snapshots